server:
  port: 3344

spring:
  application:
    name: cloud-config-center #注册进eureka服务器的微服务名
  cloud:
    config:
      server:
        git:
          skipSslValidation: true
          #uri: git@github.com:qymh233/springcloud-config.git #github上的git仓库名字
          uri: https://github.com/qymh233/springcloud-config.git
          ###搜索目录
          search-paths:
            - springcloud-config
          password: 19980714abcde233
          username: 1826859775@qq.com
      ###读取分支
      label: main
  #rabbitmq相关配置
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest

#服务注册到eureka地址
eureka:
  client:
    service-url:
      defaultZone: http://localhost:7001/eureka

#rabbitmq相关配置，暴露bus刷新配置的端点
management:
  endpoints: #暴露bus刷新配置的端点
    web:
      exposure:
        include: 'bus-refresh'



